/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DesignRouteImport } from './routes/[_]design'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AppGuildsGuildIdRouteImport } from './routes/_app.guilds.$guildId'
import { Route as AppInviteCodeRouteImport } from './routes/_app.invite.$code'
import { Route as AppGuildsGuildIdIndexRouteImport } from './routes/_app.guilds.$guildId.index'
import { Route as AppGuildsGuildIdChannelsChannelIdRouteImport } from './routes/_app.guilds.$guildId.channels.$channelId'
import { Route as AppGuildsGuildIdSettingsSectionRouteImport } from './routes/_app.guilds.$guildId.settings.$section'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/_design',
  path: '/_design',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppGuildsGuildIdRoute = AppGuildsGuildIdRouteImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteCodeRoute = AppInviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsGuildIdIndexRoute = AppGuildsGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGuildsGuildIdRoute,
} as any)
const AppGuildsGuildIdChannelsChannelIdRoute =
  AppGuildsGuildIdChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => AppGuildsGuildIdRoute,
  } as any)
const AppGuildsGuildIdSettingsSectionRoute =
  AppGuildsGuildIdSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => AppGuildsGuildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/_design': typeof DesignRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/guilds/$guildId': typeof AppGuildsGuildIdRouteWithChildren
  '/invite/$code': typeof AppInviteCodeRoute
  '/guilds/$guildId/': typeof AppGuildsGuildIdIndexRoute
  '/guilds/$guildId/channels/$channelId': typeof AppGuildsGuildIdChannelsChannelIdRoute
  '/guilds/$guildId/settings/$section': typeof AppGuildsGuildIdSettingsSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/_design': typeof DesignRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/$code': typeof AppInviteCodeRoute
  '/guilds/$guildId': typeof AppGuildsGuildIdIndexRoute
  '/guilds/$guildId/channels/$channelId': typeof AppGuildsGuildIdChannelsChannelIdRoute
  '/guilds/$guildId/settings/$section': typeof AppGuildsGuildIdSettingsSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_design': typeof DesignRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/guilds/$guildId': typeof AppGuildsGuildIdRouteWithChildren
  '/_app/invite/$code': typeof AppInviteCodeRoute
  '/_app/guilds/$guildId/': typeof AppGuildsGuildIdIndexRoute
  '/_app/guilds/$guildId/channels/$channelId': typeof AppGuildsGuildIdChannelsChannelIdRoute
  '/_app/guilds/$guildId/settings/$section': typeof AppGuildsGuildIdSettingsSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_design'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/guilds/$guildId'
    | '/invite/$code'
    | '/guilds/$guildId/'
    | '/guilds/$guildId/channels/$channelId'
    | '/guilds/$guildId/settings/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_design'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/invite/$code'
    | '/guilds/$guildId'
    | '/guilds/$guildId/channels/$channelId'
    | '/guilds/$guildId/settings/$section'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_design'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_app/'
    | '/_app/guilds/$guildId'
    | '/_app/invite/$code'
    | '/_app/guilds/$guildId/'
    | '/_app/guilds/$guildId/channels/$channelId'
    | '/_app/guilds/$guildId/settings/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DesignRoute: typeof DesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_design': {
      id: '/_design'
      path: '/_design'
      fullPath: '/_design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/guilds/$guildId': {
      id: '/_app/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof AppGuildsGuildIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite/$code': {
      id: '/_app/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof AppInviteCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$guildId/': {
      id: '/_app/guilds/$guildId/'
      path: '/'
      fullPath: '/guilds/$guildId/'
      preLoaderRoute: typeof AppGuildsGuildIdIndexRouteImport
      parentRoute: typeof AppGuildsGuildIdRoute
    }
    '/_app/guilds/$guildId/channels/$channelId': {
      id: '/_app/guilds/$guildId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/guilds/$guildId/channels/$channelId'
      preLoaderRoute: typeof AppGuildsGuildIdChannelsChannelIdRouteImport
      parentRoute: typeof AppGuildsGuildIdRoute
    }
    '/_app/guilds/$guildId/settings/$section': {
      id: '/_app/guilds/$guildId/settings/$section'
      path: '/settings/$section'
      fullPath: '/guilds/$guildId/settings/$section'
      preLoaderRoute: typeof AppGuildsGuildIdSettingsSectionRouteImport
      parentRoute: typeof AppGuildsGuildIdRoute
    }
  }
}

interface AppGuildsGuildIdRouteChildren {
  AppGuildsGuildIdIndexRoute: typeof AppGuildsGuildIdIndexRoute
  AppGuildsGuildIdChannelsChannelIdRoute: typeof AppGuildsGuildIdChannelsChannelIdRoute
  AppGuildsGuildIdSettingsSectionRoute: typeof AppGuildsGuildIdSettingsSectionRoute
}

const AppGuildsGuildIdRouteChildren: AppGuildsGuildIdRouteChildren = {
  AppGuildsGuildIdIndexRoute: AppGuildsGuildIdIndexRoute,
  AppGuildsGuildIdChannelsChannelIdRoute:
    AppGuildsGuildIdChannelsChannelIdRoute,
  AppGuildsGuildIdSettingsSectionRoute: AppGuildsGuildIdSettingsSectionRoute,
}

const AppGuildsGuildIdRouteWithChildren =
  AppGuildsGuildIdRoute._addFileChildren(AppGuildsGuildIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppGuildsGuildIdRoute: typeof AppGuildsGuildIdRouteWithChildren
  AppInviteCodeRoute: typeof AppInviteCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppGuildsGuildIdRoute: AppGuildsGuildIdRouteWithChildren,
  AppInviteCodeRoute: AppInviteCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DesignRoute: DesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
