/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DesignRouteImport } from './routes/[_]design'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFriendsRouteImport } from './routes/_app.friends'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AppFriendsIndexRouteImport } from './routes/_app.friends.index'
import { Route as AppFriendsBlockedRouteImport } from './routes/_app.friends.blocked'
import { Route as AppFriendsPendingRouteImport } from './routes/_app.friends.pending'
import { Route as AppGuildsGuildIdRouteImport } from './routes/_app.guilds.$guildId'
import { Route as AppInviteCodeRouteImport } from './routes/_app.invite.$code'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppGuildsGuildIdIndexRouteImport } from './routes/_app.guilds.$guildId.index'
import { Route as AppGuildsGuildIdChannelsChannelIdRouteImport } from './routes/_app.guilds.$guildId.channels.$channelId'
import { Route as AppGuildsGuildIdSettingsSectionRouteImport } from './routes/_app.guilds.$guildId.settings.$section'
import { Route as AppGuildsGuildIdChannelsChannelIdIndexRouteImport } from './routes/_app.guilds.$guildId.channels.$channelId.index'
import { Route as AppGuildsGuildIdChannelsChannelIdSettingsTabRouteImport } from './routes/_app.guilds.$guildId.channels.$channelId.settings.$tab'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/_design',
  path: '/_design',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppFriendsIndexRoute = AppFriendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFriendsRoute,
} as any)
const AppFriendsBlockedRoute = AppFriendsBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AppFriendsRoute,
} as any)
const AppFriendsPendingRoute = AppFriendsPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppFriendsRoute,
} as any)
const AppGuildsGuildIdRoute = AppGuildsGuildIdRouteImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteCodeRoute = AppInviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsGuildIdIndexRoute = AppGuildsGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGuildsGuildIdRoute,
} as any)
const AppGuildsGuildIdChannelsChannelIdRoute =
  AppGuildsGuildIdChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => AppGuildsGuildIdRoute,
  } as any)
const AppGuildsGuildIdSettingsSectionRoute =
  AppGuildsGuildIdSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => AppGuildsGuildIdRoute,
  } as any)
const AppGuildsGuildIdChannelsChannelIdIndexRoute =
  AppGuildsGuildIdChannelsChannelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppGuildsGuildIdChannelsChannelIdRoute,
  } as any)
const AppGuildsGuildIdChannelsChannelIdSettingsTabRoute =
  AppGuildsGuildIdChannelsChannelIdSettingsTabRouteImport.update({
    id: '/settings/$tab',
    path: '/settings/$tab',
    getParentRoute: () => AppGuildsGuildIdChannelsChannelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/_design': typeof DesignRoute
  '/friends': typeof AppFriendsRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/friends/blocked': typeof AppFriendsBlockedRoute
  '/friends/pending': typeof AppFriendsPendingRoute
  '/guilds/$guildId': typeof AppGuildsGuildIdRouteWithChildren
  '/invite/$code': typeof AppInviteCodeRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/friends/': typeof AppFriendsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/guilds/$guildId/': typeof AppGuildsGuildIdIndexRoute
  '/guilds/$guildId/channels/$channelId': typeof AppGuildsGuildIdChannelsChannelIdRouteWithChildren
  '/guilds/$guildId/settings/$section': typeof AppGuildsGuildIdSettingsSectionRoute
  '/guilds/$guildId/channels/$channelId/': typeof AppGuildsGuildIdChannelsChannelIdIndexRoute
  '/guilds/$guildId/channels/$channelId/settings/$tab': typeof AppGuildsGuildIdChannelsChannelIdSettingsTabRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/_design': typeof DesignRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/friends/blocked': typeof AppFriendsBlockedRoute
  '/friends/pending': typeof AppFriendsPendingRoute
  '/invite/$code': typeof AppInviteCodeRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/friends': typeof AppFriendsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/guilds/$guildId': typeof AppGuildsGuildIdIndexRoute
  '/guilds/$guildId/settings/$section': typeof AppGuildsGuildIdSettingsSectionRoute
  '/guilds/$guildId/channels/$channelId': typeof AppGuildsGuildIdChannelsChannelIdIndexRoute
  '/guilds/$guildId/channels/$channelId/settings/$tab': typeof AppGuildsGuildIdChannelsChannelIdSettingsTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_design': typeof DesignRoute
  '/_app/friends': typeof AppFriendsRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/friends/blocked': typeof AppFriendsBlockedRoute
  '/_app/friends/pending': typeof AppFriendsPendingRoute
  '/_app/guilds/$guildId': typeof AppGuildsGuildIdRouteWithChildren
  '/_app/invite/$code': typeof AppInviteCodeRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/friends/': typeof AppFriendsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/guilds/$guildId/': typeof AppGuildsGuildIdIndexRoute
  '/_app/guilds/$guildId/channels/$channelId': typeof AppGuildsGuildIdChannelsChannelIdRouteWithChildren
  '/_app/guilds/$guildId/settings/$section': typeof AppGuildsGuildIdSettingsSectionRoute
  '/_app/guilds/$guildId/channels/$channelId/': typeof AppGuildsGuildIdChannelsChannelIdIndexRoute
  '/_app/guilds/$guildId/channels/$channelId/settings/$tab': typeof AppGuildsGuildIdChannelsChannelIdSettingsTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_design'
    | '/friends'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/friends/blocked'
    | '/friends/pending'
    | '/guilds/$guildId'
    | '/invite/$code'
    | '/settings/account'
    | '/settings/profile'
    | '/settings/security'
    | '/friends/'
    | '/settings/'
    | '/guilds/$guildId/'
    | '/guilds/$guildId/channels/$channelId'
    | '/guilds/$guildId/settings/$section'
    | '/guilds/$guildId/channels/$channelId/'
    | '/guilds/$guildId/channels/$channelId/settings/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_design'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/friends/blocked'
    | '/friends/pending'
    | '/invite/$code'
    | '/settings/account'
    | '/settings/profile'
    | '/settings/security'
    | '/friends'
    | '/settings'
    | '/guilds/$guildId'
    | '/guilds/$guildId/settings/$section'
    | '/guilds/$guildId/channels/$channelId'
    | '/guilds/$guildId/channels/$channelId/settings/$tab'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_design'
    | '/_app/friends'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_app/'
    | '/_app/friends/blocked'
    | '/_app/friends/pending'
    | '/_app/guilds/$guildId'
    | '/_app/invite/$code'
    | '/_app/settings/account'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/friends/'
    | '/_app/settings/'
    | '/_app/guilds/$guildId/'
    | '/_app/guilds/$guildId/channels/$channelId'
    | '/_app/guilds/$guildId/settings/$section'
    | '/_app/guilds/$guildId/channels/$channelId/'
    | '/_app/guilds/$guildId/channels/$channelId/settings/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DesignRoute: typeof DesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_design': {
      id: '/_design'
      path: '/_design'
      fullPath: '/_design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/friends/': {
      id: '/_app/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof AppFriendsIndexRouteImport
      parentRoute: typeof AppFriendsRoute
    }
    '/_app/friends/blocked': {
      id: '/_app/friends/blocked'
      path: '/blocked'
      fullPath: '/friends/blocked'
      preLoaderRoute: typeof AppFriendsBlockedRouteImport
      parentRoute: typeof AppFriendsRoute
    }
    '/_app/friends/pending': {
      id: '/_app/friends/pending'
      path: '/pending'
      fullPath: '/friends/pending'
      preLoaderRoute: typeof AppFriendsPendingRouteImport
      parentRoute: typeof AppFriendsRoute
    }
    '/_app/guilds/$guildId': {
      id: '/_app/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof AppGuildsGuildIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite/$code': {
      id: '/_app/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof AppInviteCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$guildId/': {
      id: '/_app/guilds/$guildId/'
      path: '/'
      fullPath: '/guilds/$guildId/'
      preLoaderRoute: typeof AppGuildsGuildIdIndexRouteImport
      parentRoute: typeof AppGuildsGuildIdRoute
    }
    '/_app/guilds/$guildId/channels/$channelId': {
      id: '/_app/guilds/$guildId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/guilds/$guildId/channels/$channelId'
      preLoaderRoute: typeof AppGuildsGuildIdChannelsChannelIdRouteImport
      parentRoute: typeof AppGuildsGuildIdRoute
    }
    '/_app/guilds/$guildId/settings/$section': {
      id: '/_app/guilds/$guildId/settings/$section'
      path: '/settings/$section'
      fullPath: '/guilds/$guildId/settings/$section'
      preLoaderRoute: typeof AppGuildsGuildIdSettingsSectionRouteImport
      parentRoute: typeof AppGuildsGuildIdRoute
    }
    '/_app/guilds/$guildId/channels/$channelId/': {
      id: '/_app/guilds/$guildId/channels/$channelId/'
      path: '/'
      fullPath: '/guilds/$guildId/channels/$channelId/'
      preLoaderRoute: typeof AppGuildsGuildIdChannelsChannelIdIndexRouteImport
      parentRoute: typeof AppGuildsGuildIdChannelsChannelIdRoute
    }
    '/_app/guilds/$guildId/channels/$channelId/settings/$tab': {
      id: '/_app/guilds/$guildId/channels/$channelId/settings/$tab'
      path: '/settings/$tab'
      fullPath: '/guilds/$guildId/channels/$channelId/settings/$tab'
      preLoaderRoute: typeof AppGuildsGuildIdChannelsChannelIdSettingsTabRouteImport
      parentRoute: typeof AppGuildsGuildIdChannelsChannelIdRoute
    }
  }
}

interface AppFriendsRouteChildren {
  AppFriendsBlockedRoute: typeof AppFriendsBlockedRoute
  AppFriendsPendingRoute: typeof AppFriendsPendingRoute
  AppFriendsIndexRoute: typeof AppFriendsIndexRoute
}

const AppFriendsRouteChildren: AppFriendsRouteChildren = {
  AppFriendsBlockedRoute: AppFriendsBlockedRoute,
  AppFriendsPendingRoute: AppFriendsPendingRoute,
  AppFriendsIndexRoute: AppFriendsIndexRoute,
}

const AppFriendsRouteWithChildren = AppFriendsRoute._addFileChildren(
  AppFriendsRouteChildren,
)

interface AppGuildsGuildIdChannelsChannelIdRouteChildren {
  AppGuildsGuildIdChannelsChannelIdIndexRoute: typeof AppGuildsGuildIdChannelsChannelIdIndexRoute
  AppGuildsGuildIdChannelsChannelIdSettingsTabRoute: typeof AppGuildsGuildIdChannelsChannelIdSettingsTabRoute
}

const AppGuildsGuildIdChannelsChannelIdRouteChildren: AppGuildsGuildIdChannelsChannelIdRouteChildren =
  {
    AppGuildsGuildIdChannelsChannelIdIndexRoute:
      AppGuildsGuildIdChannelsChannelIdIndexRoute,
    AppGuildsGuildIdChannelsChannelIdSettingsTabRoute:
      AppGuildsGuildIdChannelsChannelIdSettingsTabRoute,
  }

const AppGuildsGuildIdChannelsChannelIdRouteWithChildren =
  AppGuildsGuildIdChannelsChannelIdRoute._addFileChildren(
    AppGuildsGuildIdChannelsChannelIdRouteChildren,
  )

interface AppGuildsGuildIdRouteChildren {
  AppGuildsGuildIdIndexRoute: typeof AppGuildsGuildIdIndexRoute
  AppGuildsGuildIdChannelsChannelIdRoute: typeof AppGuildsGuildIdChannelsChannelIdRouteWithChildren
  AppGuildsGuildIdSettingsSectionRoute: typeof AppGuildsGuildIdSettingsSectionRoute
}

const AppGuildsGuildIdRouteChildren: AppGuildsGuildIdRouteChildren = {
  AppGuildsGuildIdIndexRoute: AppGuildsGuildIdIndexRoute,
  AppGuildsGuildIdChannelsChannelIdRoute:
    AppGuildsGuildIdChannelsChannelIdRouteWithChildren,
  AppGuildsGuildIdSettingsSectionRoute: AppGuildsGuildIdSettingsSectionRoute,
}

const AppGuildsGuildIdRouteWithChildren =
  AppGuildsGuildIdRoute._addFileChildren(AppGuildsGuildIdRouteChildren)

interface AppRouteChildren {
  AppFriendsRoute: typeof AppFriendsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppGuildsGuildIdRoute: typeof AppGuildsGuildIdRouteWithChildren
  AppInviteCodeRoute: typeof AppInviteCodeRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFriendsRoute: AppFriendsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppGuildsGuildIdRoute: AppGuildsGuildIdRouteWithChildren,
  AppInviteCodeRoute: AppInviteCodeRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DesignRoute: DesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
